version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    default_reviewers:
      - 'pataruco'
    default_labels:
      - 'dependabot 🤖'
    allowed_updates:
      - match:
          update_type: 'security'
