name: Cloud Run CI dev

on:
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - 'api/*'
      - '!infrastructure/*'
      - '!upload-cli/*'

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: martin-blanco-api-dev
  RUN_REGION: europe-west1
  SERVICE_NAME: martin-blanco-api
  BUCKET_NAME: martin-blanco

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          # version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY}}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID

      # Build and push image to Google Container Registry
      - name: Build
        run: |
          gcloud builds submit ./api -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --set-env-vars BUCKET_NAME=${BUCKET_NAME} \
            --platform managed
