name: CI Dev
on:
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - 'api/*'
      - '!infrastructure/*'
      - '!shared/*'
      - '!upload-cli/*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10']
    name: Installing node
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.2
      - run: |
          cd api
          yarn && yarn build
        shell: bash
        env:
          GITHUB_REGISTRY_AUTH_TOKEN: ${{ secrets.GITHUB_REGISTRY_AUTH_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: api
          path: ./api/dist/
  deploy:
    runs-on: ubuntu-latest
    name: Logging into GCP
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        name: Download Artifact
        with:
          name: api
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: |
          cd api
          ls -lah 
          cat .npmrc
          yarn deploy:dev
        shell: bash
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
