name: Production pipeline
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10']
    name: Installing node
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.2
      - run: yarn && yarn build
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: api
          path: ./dist/
  loginInGCP:
    runs-on: ubuntu-latest
    name: Logging into GCP
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        name: Download Artifact
        with:
          name: api
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL_PROD }}
          service_account_key: ${{ secrets.GCP_SA_KEY_PROD }}
      - run: |
          yarn deploy:prod
        shell: bash
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME_PROD }}
